# Generated by Django 5.0.6 on 2024-07-05 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_add_repository_project_email_project_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='add_repository',
        ),
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='token',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project')),
            ],
        ),
    ]
