# Generated by Django 5.0.6 on 2024-07-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_add_repository_remove_project_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('jira', 'Jira')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='projects.project')),
            ],
        ),
    ]
