# Generated by Django 5.0.6 on 2024-07-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_repository_project_alter_tracker_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='url',
            field=models.CharField(),
        ),
    ]
