# Generated by Django 5.0.6 on 2024-07-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_repository_email_alter_repository_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='email',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='token',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='type',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=10),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='email',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='token',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='type',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('jira', 'Jira')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='url',
            field=models.CharField(blank=True),
        ),
    ]
